package com.karimandco.pdf;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Image;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author t.leal
 */
public class PanelPDF extends javax.swing.JPanel {

    /**
     * Crée le composant PanelPDF.
     * 
     */
    public PanelPDF() {
        initComponents();
        lienPDF="";
        jLabelLienPDF.setForeground(Color.red);
        jLabelLienPDF.setText("Choisissez un dossier");
    }
    
    public PanelPDF(String nom, String prenom, String numero, String courriel, Date dateDeNaissance, String[] experience, String[] formation, String[] informatique, String[] langues, String[] centreInteret, Image image){
        initComponents();
        lienPDF="";
        jLabelLienPDF.setForeground(Color.red);
        jLabelLienPDF.setText("Choisissez un dossier");
        modifieValeur(nom, prenom, numero, courriel, dateDeNaissance, experience, formation, informatique, langues, centreInteret, image);
    }

    //Mutateur et accesseur
    
    /**
     * Modifie le nom.
     * @param nom 
     */
    public void setNom(String nom) {
        this.nom = nom;
    }
    /**
     * Modifie le prénom.
     * @param prenom 
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    /**
     * Modifie le numéro.
     * @param numero 
     */
    public void setNumero(String numero) {
        this.numero = numero;
    }
    
    /**
     * Modifie les valeurs du CV.
     * @param nom
     * @param prenom
     * @param numero 
     */
    public void modifieValeur(String nom, String prenom, String numero, String courriel, Date dateDeNaissance, String[] experience, String[] formation, String[] informatique, String[] langues, String[] centreInteret, Image image){
        this.nom=nom;
        this.prenom=prenom;
        this.numero=numero;
        this.courriel=courriel;
        this.dateDeNaissance=dateDeNaissance;
        this.experience=experience;
        this.formation=formation;
        this.informatique=informatique;
        this.langues=langues;
        this.centreInteret=centreInteret;
        this.image=image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLienPDF = new javax.swing.JLabel();
        jButtonChoisirBouton = new javax.swing.JButton();
        jButtonEnregistrerPDF = new javax.swing.JButton();

        jLabelLienPDF.setText("jLabel1");

        jButtonChoisirBouton.setText("Choisir un dossier");
        jButtonChoisirBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChoisirBoutonMouseClicked(evt);
            }
        });

        jButtonEnregistrerPDF.setText("Enregistrer");
        jButtonEnregistrerPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnregistrerPDFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLienPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChoisirBouton)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnregistrerPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLienPDF)
                    .addComponent(jButtonChoisirBouton)
                    .addComponent(jButtonEnregistrerPDF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChoisirBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChoisirBoutonMouseClicked
        int result;
        File dossierChoisi;
        String lienDossier;
        
        result = selectPDF.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            dossierChoisi=selectPDF.getSelectedFile();
            lienDossier = dossierChoisi.toString();
            this.lienPDF=lienDossier;
            jLabelLienPDF.setForeground(Color.black);
            jLabelLienPDF.setText(lienPDF);
        } else if(result == JFileChooser.CANCEL_OPTION) {
//            System.out.println("PAS OK");
        }
    }//GEN-LAST:event_jButtonChoisirBoutonMouseClicked

    private void jButtonEnregistrerPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnregistrerPDFMouseClicked
        Pdf pdf = new Pdf(nom, prenom, numero, courriel, lienPDF, dateDeNaissance, experience, formation, informatique, langues, centreInteret, image);
        System.out.println(lienPDF);
        if (pdf.verifPDF()) {
            try {
                pdf.genererPDF();
                JOptionPane.showMessageDialog(this, "cv.pdf a été enregistré dans "+lienPDF);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Erreur","PDF",JOptionPane.ERROR_MESSAGE);
            } catch (BadElementException ex) {
                Logger.getLogger(PanelPDF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PanelPDF.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vous devez sélectionné un dossier.","PDF",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEnregistrerPDFMouseClicked


    public String lienPDF;
    public choisirDossier selectPDF = new choisirDossier();
    private String nom="";
    private String prenom="";
    private String numero="";
    private String courriel="";
    private Date dateDeNaissance=null;
    private String[] experience;
    private String[] formation;
    private String[] informatique;
    private String[] langues;
    private String[] centreInteret;
    private Image image;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoisirBouton;
    private javax.swing.JButton jButtonEnregistrerPDF;
    private javax.swing.JLabel jLabelLienPDF;
    // End of variables declaration//GEN-END:variables
}
