/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.pdf;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author t.leal
 */
public class PanelPDF extends javax.swing.JPanel {

    /**
     * Creates new form PanelPDF
     */
    public PanelPDF() {
        initComponents();
        lienPDF="";
        jLabelLienPDF.setForeground(Color.red);
        jLabelLienPDF.setText("Choisissez un dossier");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLienPDF = new javax.swing.JLabel();
        jButtonChoisirBouton = new javax.swing.JButton();
        jButtonEnregistrerPDF = new javax.swing.JButton();

        jLabelLienPDF.setText("jLabel1");

        jButtonChoisirBouton.setText("Choisir un dossier");
        jButtonChoisirBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChoisirBoutonMouseClicked(evt);
            }
        });

        jButtonEnregistrerPDF.setText("Enregistrer");
        jButtonEnregistrerPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnregistrerPDFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLienPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChoisirBouton)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnregistrerPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLienPDF)
                    .addComponent(jButtonChoisirBouton)
                    .addComponent(jButtonEnregistrerPDF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChoisirBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChoisirBoutonMouseClicked
        int result;
        File dossierChoisi;
        String lienDossier;
        
        result = selectPDF.getChoisirDossier().showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            dossierChoisi=selectPDF.getChoisirDossier().getSelectedFile();
            lienDossier = dossierChoisi.toString();
            this.lienPDF=lienDossier;
            jLabelLienPDF.setForeground(Color.black);
            jLabelLienPDF.setText(lienPDF);
        } else if(result == JFileChooser.CANCEL_OPTION) {
//            System.out.println("PAS OK");
        }
    }//GEN-LAST:event_jButtonChoisirBoutonMouseClicked

    private void jButtonEnregistrerPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnregistrerPDFMouseClicked
        if (lienPDF!="") {
            JOptionPane.showConfirmDialog(this, "Ok, c'est bon");
        } else {
            JOptionPane.showConfirmDialog(this, "Pas ok, c'est pas bon");
        }
    }//GEN-LAST:event_jButtonEnregistrerPDFMouseClicked


    public String lienPDF;
    public SelectionnerPDF selectPDF = new SelectionnerPDF();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoisirBouton;
    private javax.swing.JButton jButtonEnregistrerPDF;
    private javax.swing.JLabel jLabelLienPDF;
    // End of variables declaration//GEN-END:variables
}
